#!/bin/bash

SBT_BOOT_DIR=$HOME/.sbt/boot/

if [ ! -d "$SBT_BOOT_DIR" ]; then
  mkdir -p $SBT_BOOT_DIR
fi

## We cat /dev/null into this to stop Teamcity from hanging on any interactions
cat /dev/null | java -Dfile.encoding=UTF8 -Xmx1G -XX:MaxPermSize=250m -XX:+UseCompressedOops \
    -Dhttp.proxyHost=devscreen.gudev.gnl -Dhttp.proxyPort=3128 \
    -Dsbt.log.noformat=true \
    -Dbuild.number="$BUILD_NUMBER" \
    -Dbuild.vcs.number="$BUILD_VCS_NUMBER" \
    -Djava.awt.headless=true \
    -Dint.service.domain="integration.build" \
    -jar sbt-launch-*.jar "$@"

